### ISSUE TITLE
Affine map in python provides nans

### ISSUE THREAD

**Issue by rubiop** [MeasureTransport/MParT#327] opened 2023-04-15 17:05 UTC
At least the `.Evaluate()` method for `AffineMap` defined in python is buggy providing nans at random computation time. In my experience it doesn't depend on the value of the coefficients nor the points where the map is evaluated. For the same example in matlab I have no issue so there is probably something weird happening with pybind.

In this example:

```
import numpy as np
import os
os.environ['KOKKOS_NUM_THREADS'] = '8'
import mpart as mt
print('Kokkos is using', mt.Concurrency(), 'threads')
np.random.seed(1)
samples = np.random.randn(2,200000)
A = np.array([[ 3.97678524, 0.        ],
       [ 4.55559914,  0.01547669]])
c = np.array([ -7.94509863, -18.88155037])
L = mt.AffineMap(np.asfortranarray(A),np.asfortranarray(c))
samples_st = L.Evaluate(samples)
print(np.mean(samples_st))
```

The print function at the end will return nan if there is any nan returned by the `AffineMap`.

**Comment by mparno** [comment] 2023-04-17 15:12
@rubiop I'm having a hard time reproducing this on my machine, but could you try something for me?  Instead of calling `np.asfortranarray(A)` inside the `AffineMap` constructor, could you add it directly to the definitions of `A` and `c`?   The updates should look like this:
```python
A = np.asfortranarray(np.array([[ 3.97678524, 0.        ],
       [ 4.55559914,  0.01547669]]))
c = np.asfortranarray(np.array([ -7.94509863, -18.88155037]))
L = mt.AffineMap(A,c)
```

I suspect that `np.asfortranarray` is returning a new copy of `A` or `c`, which goes out of scope after the call to `AffineMap`.   Because `AffineMap` isn't making a copy itself, it will therefore end up pointing at some random uninitialized memory location where the temporary output of `asfortranarray` was stored.     

I think the solution is to update `AffineMap` so we don't need to call `asfortranarray` as all.  I'll look into this as an option, but will wait until someone can verify that this is the issue before submitting a pull request.

**Comment by rubiop** [comment] 2023-04-17 15:24
Thanks for looking into this @mparno. The issue might be hard to catch. Try this example:

```
import numpy as np
import os
os.environ['KOKKOS_NUM_THREADS'] = '8'

import mpart as mt
print('Kokkos is using', mt.Concurrency(), 'threads')

np.random.seed(8)

def output(sigma_w,sigma_i,z_iw):
    Rz_iw=1/np.sqrt(4*z_iw**2+1);
    out=sigma_i*(1-Rz_iw)+sigma_w*(Rz_iw);
    return out

sigma_w=2500; 
sigma_i=22;
mu0 = 2;
std0 = 0.25;
std_m = 63
N=20000; # total number of samples
X = mu0 + std0*np.random.randn(1,N);
Y = output(sigma_w,sigma_i,X)+std_m*np.random.randn(1,N);
samples = np.vstack((X,Y))
n_train = int(samples.shape[1]*0.8)
samples_train = samples[:,:n_train]
samples_test = samples[:,n_train:]
C = np.std(samples_train,axis=1)
A = np.asfortranarray(np.array([[1/C[0],0],[0,1/C[1]]]))
c = np.asfortranarray(-1 * np.dot(A,np.mean(samples_train,axis=1)))
L = mt.AffineMap(A,c)
samples_test_st = L.Evaluate(samples_test)
print(L.Evaluate(samples_test)[:,:4])
print(samples_test_st[:,:4])
```

The printed arrays should exhibit nans when you run the cell multiple times on a notebook. On my computer I still have issues even with your suggestion so let me know.

**Comment by mparno** [comment] 2023-04-17 16:11
@rubiop The issue should be fixed now in the `mparno/issue327` branch, but let me know if you still run into issues.

**Closed** 2023-04-17 16:55 UTC
Labels: bug, bindings
